### ISSUE TITLE
Recent change causes profile names with '.' to not be recognized or found

### ISSUE THREAD

**Issue by rvanider** [smithy-lang/smithy-typescript#1053]
https://github.com/awslabs/smithy-typescript/blob/d5eacb5153a8473b572919392e0644babd04d983/packages/shared-ini-file-loader/src/parseIni.ts#L5

While the `.` character is not cited in https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html#section-types profile names in the format of `some-account.some-role` were accepted in the aws-sdk-v2 and up until the last change to the above regular expression.

Both the aws cli, aws-sdk-v2 and the Python sdk accept this name pattern. It appears the java SDK was revised to accept these as well via https://github.com/aws/aws-sdk-java-v2/issues/389 and https://github.com/aws/aws-sdk-java-v2/pull/1538/files.

Please revise to improve consistency.

**Comment by jmalins** [comment]
This also broke the profiles generated by [granted](https://github.com/common-fate/granted), which contain a single slash: `{aws-account-name}/{role-name}`.

**Comment by jmalins** [comment]
This behavior was extremely difficult to trace because profile names containing invalid characters are silently ignored. They work in the CLI, Python SDK and Javascript SDK V2.

In Javascript SDK V3, you simply receive a `CredentialsProviderError: Could not load credentials from any providers` error without context or explanation.

**Comment by huyhua-nvg** [comment]
@trivikr unfortunately this doesn't fix the problem.
This part of the code filter out profiles with "." in name even if parseIni returns the correct ones.

https://github.com/awslabs/smithy-typescript/blob/d5eacb5153a8473b572919392e0644babd04d983/packages/shared-ini-file-loader/src/getConfigData.ts#L14C4-L32

This is how it would work in my case but I'm unaware if it introduces more regressions. 
```
    .filter(([key]) => {
      const sections = key.split(CONFIG_PREFIX_SEPARATOR);
      if (sections.length >= 2 && Object.values(IniSectionType).includes(sections[0] as IniSectionType)) {
        return true;
      }
      return false;
    })
    // replace profile prefix, if present.
    .reduce(
      (acc, [key, value]) => {
        const updatedKey = key.startsWith(IniSectionType.PROFILE) ? key.split(CONFIG_PREFIX_SEPARATOR).slice(1).join(loadSharedConfigFiles_1.CONFIG_PREFIX_SEPARATOR) : key;
        acc[updatedKey] = value;
        return acc;
      },
      {
        // Populate default profile, if present.
        ...(data.default && { default: data.default }),
      } as ParsedIniData
    );
```

**Comment by trivikr** [comment]
Reproduction code

```js
$ cat test.mjs
import { DynamoDB } from "@aws-sdk/client-dynamodb"; // v3.465.0

const client = new DynamoDB();
console.log(await client.listTables());

$ cat ~/.aws/credentials
[foo.bar]
aws_access_key_id = <REDACTED>
aws_secret_access_key = <REDACTED>

[foo@bar]
aws_access_key_id = <REDACTED>
aws_secret_access_key = <REDACTED>

$ cat ~/.aws/config 
[profile foo.bar]
region = eu-west-2

[profile foo@bar]
region = eu-west-2
```

Output:

```console
$ AWS_PROFILE=foo@bar node test.mjs
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'VQR3QO4RRKAFCD5DR2IL0OD173VV4KQNSO5AEMVJF66Q9ASUAAJG',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  TableNames: []
}

$ AWS_PROFILE=foo.bar node test.mjs
/local/home/trivikr/workspace/test/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10
        throw new Error("Region is missing");
              ^

Error: Region is missing
    at default (/local/home/trivikr/workspace/test/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/config.js:10:15)
    at /local/home/trivikr/workspace/test/node_modules/@smithy/node-config-provider/dist-cjs/fromStatic.js:6:83
    at /local/home/trivikr/workspace/test/node_modules/@smithy/node-config-provider/node_modules/@smithy/property-provider/dist-cjs/chain.js:12:39
    at async coalesceProvider (/local/home/trivikr/workspace/test/node_modules/@smithy/node-config-provider/node_modules/@smithy/property-provider/dist-cjs/memoize.js:14:24)
    at async /local/home/trivikr/workspace/test/node_modules/@smithy/node-config-provider/node_modules/@smithy/property-provider/dist-cjs/memoize.js:26:28
    at async useFipsEndpoint (/local/home/trivikr/workspace/test/node_modules/@smithy/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:21:74)
    at async resolveParams (/local/home/trivikr/workspace/test/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:37:40)
    at async getEndpointFromInstructions (/local/home/trivikr/workspace/test/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:15:28)
    at async /local/home/trivikr/workspace/test/node_modules/@smithy/middleware-endpoint/dist-cjs/endpointMiddleware.js:9:26
    at async /local/home/trivikr/workspace/test/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26

Node.js v18.18.2
```

**Comment by trivikr** [comment]
Reproduction code

```js
$ cat test.mjs 
import { loadSharedConfigFiles } from "@smithy/shared-ini-file-loader"; // v2.2.6
console.log(await loadSharedConfigFiles());

$ cat ~/.aws/credentials
[foo.bar]
aws_access_key_id = aws_access_key_id
aws_secret_access_key = aws_secret_access_key

[foo@bar]
aws_access_key_id = aws_access_key_id
aws_secret_access_key = aws_secret_access_key

$ cat ~/.aws/config
[profile foo.bar]
region = eu-west-2

[profile foo@bar]
region = eu-west-2
```

Output
```console
$ node test.mjs 
{
  configFile: { 'foo@bar': { region: 'eu-west-2' } },
  credentialsFile: {
    'foo.bar': {
      aws_access_key_id: 'aws_access_key_id',
      aws_secret_access_key: 'aws_secret_access_key'
    },
    'foo@bar': {
      aws_access_key_id: 'aws_access_key_id',
      aws_secret_access_key: 'aws_secret_access_key'
    }
  }
}
```

The value at configFile key should be
```
{
  'foo.bar': { region: 'eu-west-2' },
  'foo@bar': { region: 'eu-west-2' }
}
```
