### ISSUE TITLE
Invalid S3 arn error thrown for valid format

### ISSUE THREAD

**Issue by FelixMarcus** [smithy-lang/smithy-typescript#1121]
### What?

Smithy middleware-endpoint is unable to properly recognise an S3 bucket arn following the format:

`arn:aws:s3:::bucket_name`

...despite it being the [the expected standard](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-arn-format.html).

Instead, [it will throw an error](https://github.com/smithy-lang/smithy-typescript/blob/f0ff3b7cdb93ce607c3873bab9a553566e0aec0b/packages/middleware-endpoint/src/service-customizations/s3.ts#L64) of `Invalid ARN: ${bucketName} was an invalid ARN.`

### Expected Behaviour

S3 ARN values without an account id should be valid and thus not throw an error.

### Where?

Tested on:

node@v18.19.0

Using:
- @aws-sdk/client-s3@3.472.0
- @aws-sdk/middleware-sdk-s3@3.470.0
- @smithy/middleware-endpoint@2.2.3

### Example

N.B. `s3BucketExampleArn` is passed in via cloudformation as an environment variable, and shows up correctly in the logs - matching an existing bucket in the accounts.

```
import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3';

const input = {
      Body: JSON.stringify(payloads),
      Bucket: s3BucketExampleArn,
      Key: `example-key`,
    };
const command = new PutObjectCommand(input);
await this.s3Client.send(command);
```

```
/usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/service-customizations/s3.js:39
        throw new Error(`Invalid ARN: ${bucketName} was an invalid ARN.`);
              ^
Error: Invalid ARN: arn:aws:s3:::s3BucketExampleArn was an invalid ARN.
    at isArnBucketName (/usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/service-customizations/s3.js:39:15)
    at resolveParamsForS3 (/usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/service-customizations/s3.js:9:37)
    at resolveParams (/usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:47:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getEndpointFromInstructions (/usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:15:28)
    at async /usr/src/app/node_modules/@smithy/middleware-endpoint/dist-cjs/endpointMiddleware.js:9:26
    at async /usr/src/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
    at async /usr/src/app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
    at async /usr/src/app/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

**Comment by bitIO** [comment]
It seems this function https://github.com/smithy-lang/smithy-typescript/blob/3d9d6038a44d513f4362cecd741ed23e320960a4/packages/middleware-endpoint/src/service-customizations/s3.ts#L61 is not following the standard since it expects the account to be present even though `arn:aws:s3:::my-bucket` is a valid arn
