### ISSUE TITLE
Duplicate middleware name 'NewRelicHeader'

### ISSUE THREAD

**Issue by Maxwell2022** [smithy-lang/smithy-typescript#1236]
I'm getting this error when starting our service. I looked at [this closed issue](https://github.com/newrelic/node-newrelic/issues/1688#issuecomment-1644853787) but we are using version 11 of the agent so I don't think this is related.

```
{
      "type": "Error",
      "message": "Duplicate middleware name 'NewRelicHeader'",
      "stack":
          Error: Duplicate middleware name 'NewRelicHeader'
              at Object.add (/app/node_modules/.pnpm/@smithy+middleware-stack@2.1.1/node_modules/@smithy/middleware-stack/dist-cjs/index.js:178:19)
              at _DynamoDBDocumentClient.wrappedSend (/app/node_modules/.pnpm/@newrelic+aws-sdk@7.1.0/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:58:32)
              at ****Repository.put***** (/app/dist/src/modules/*****/*****.repository.js:116:28)
              at ****Repository.create***** (/app/dist/src/modules/*****/*****.repository.js:40:20)
              at ****Service.create***** (/app/dist/src/modules/*****/*****.service.js:26:61)
              at ****Resolver.complete***** (/app/dist/src/modules/*****/resolvers/complete*****.resolver.js:39:39)
              at /app/node_modules/.pnpm/@nestjs+core@9.3.12_@nestjs+common@9.3.12_@nestjs+platform-express@9.3.12_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/helpers/external-context-creator.js:67:33
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
```

**Comment by kuhe** [comment]
This appears to be an error caused by trying to add the same middleware more than once without specifying `override: true`, but it is related to downstream code in another library.

Please ask the library authors to check the usage of the MiddlewareStack API.
