### ISSUE TITLE
Creating S3Client fails with Region Missing Error

### ISSUE THREAD

**Issue by briandee** [smithy-lang/smithy-typescript#1282]
Details of Environment
node js version 20.10.0 
@aws-sdk/client-s3": "^3.540.0,
@smithy/node-http-handler": "^2.5.0"
Typescript version 5.3.3

I am attempting to create an S3Client in order to upload files to my S3 bucket. However, the code fails with the following error: I am clearly providing the region as a property of the client.

Error is Error: Region is missing
at default (/home/app/src/node_modules/@smithy/config-resolver/dist-cjs/index.js:117:11)
at /home/app/src/node_modules/@smithy/node-config-provider/dist-cjs/index.js:72:104
at /home/app/src/node_modules/@smithy/property-provider/dist-cjs/index.js:79:33
at async coalesceProvider (/home/app/src/node_modules/@smithy/property-provider/dist-cjs/index.js:106:18)
at async /home/app/src/node_modules/@smithy/property-provider/dist-cjs/index.js:117:20
at async region (/home/app/src/node_modules/@smithy/config-resolver/dist-cjs/index.js:142:30)
at async /home/app/src/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:89:28
at async /home/app/src/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14
at async /home/app/src/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22

Here is the code:

```    
         import { EndpointV2} from '@aws-sdk/types'
         import { NodeHttpHandler } from '@smithy/node-http-handler'
         import { Agent } from 'https'
         import { ConfiguredRetryStrategy } from '@smithy/util-retry'
         import { PutObjectCommand, PutObjectCommandOutput, S3Client } from '@aws-sdk/client-s3'


           getAgent(): Agent {
                 const agent = new Agent({
                        rejectUnauthorized: true,
                      });
                return agent;
            } 


           async getClient (): Promise<S3Client> {
               const agent = getAgent()
               const endPoint: EndpointV2  = {url: new URL('url')} as EndpointV2 
               const s3Config = {
                region: 'US-WEST-2',
                endpoint: endPoint,
                credentials: {
                  accessKeyId: 'myKey' ,
                  secretAccessKey: 'mySecret'
                },
               requestHandler:new NodeHttpHandler({
                  httpAgent: agent,
                  httpsAgent: agent
               }),
               retryStrategy: new ConfiguredRetryStrategy(
                   13, 3000
               )
              } 
              const client = new S3Client([s3Config);
              return client
          }

```
const s3Client = await getClient()

**Comment by briandee** [comment]
My bad, I am passing the properties as an array to the client, when I should just pass the properties 
i.e.   const client = new S3Client(s3Config) instead of    
const client = new S3Client([s3Config]);
