### ISSUE TITLE
TypeError: headers[headerName].trim is not a function

### ISSUE THREAD

**Issue by chhornponleu** [smithy-lang/smithy-typescript#1334]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@smithy/signature-v4@2.1.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@smithy/signature-v4/dist-cjs/index.js b/node_modules/@smithy/signature-v4/dist-cjs/index.js
index fd7e634..66d27b8 100644
--- a/node_modules/@smithy/signature-v4/dist-cjs/index.js
+++ b/node_modules/@smithy/signature-v4/dist-cjs/index.js
@@ -126,7 +126,12 @@ var getCanonicalHeaders = /* @__PURE__ */ __name(({ headers }, unsignableHeaders
         continue;
       }
     }
-    canonical[canonicalHeaderName] = headers[headerName].trim().replace(/\s+/g, " ");
+    if (typeof headers?.[headerName] === 'string') {
+      canonical[canonicalHeaderName] = headers[headerName].trim().replace(/\s+/g, " ");
+    }
+    else {
+      canonical[canonicalHeaderName] = headers[headerName]
+    }
   }
   return canonical;
 }, "getCanonicalHeaders");
@@ -435,8 +440,8 @@ ${(0, import_util_hex_encoding.toHex)(hashedRequest)}`;
   }
   validateResolvedCredentials(credentials) {
     if (typeof credentials !== "object" || // @ts-expect-error: Property 'accessKeyId' does not exist on type 'object'.ts(2339)
-    typeof credentials.accessKeyId !== "string" || // @ts-expect-error: Property 'secretAccessKey' does not exist on type 'object'.ts(2339)
-    typeof credentials.secretAccessKey !== "string") {
+      typeof credentials.accessKeyId !== "string" || // @ts-expect-error: Property 'secretAccessKey' does not exist on type 'object'.ts(2339)
+      typeof credentials.secretAccessKey !== "string") {
       throw new Error("Resolved credential object is not valid");
     }
   }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by joeLepper** [comment]
I'm running into the same issue when going to use the `DeleteMessageCommand` from `@aws-sdk/client-sqs`. 

```
TypeError: headers[headerName].trim is not a function
    at getCanonicalHeaders (/Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@smithy/signature-v4/dist-cjs/index.js:130:60)
    at _SignatureV4S3Express.signRequest (/Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@smithy/signature-v4/dist-cjs/index.js:493:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _AwsSdkSigV4Signer.sign (/Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@aws-sdk/core/dist-cjs/submodules/httpAuthSchemes/index.js:108:27)
    at async /Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:480:15
    at async /Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:248:18
    at async /Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22
    at async /Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14
    at async /Users/josephlepper/medicoder/intake-email-lambda/service/attachment-summarizer/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
```

In my case it seems that `x-amz-meta-received_at` is a `number` and not a `string` as this function expects.
