### ISSUE TITLE
doesn't show full trace

### ISSUE THREAD

**Issue by ORESoftware** [smithy-lang/smithy-typescript#1406]
I don't see any app code, just library code:

![image](https://github.com/user-attachments/assets/d60d9822-5726-4db4-9f56-c49416010a62)

the trace can't capture what application code caused this?

**Comment by ORESoftware** [comment]
```
   └─ 12: CHECK_WALLET_IS_MULTISIG

20:33:54.194 [error] [LocalstackCLI]: Seeding localstack failed
└─ app: company
TypeError: Invalid URL
    at new URL (node:internal/url:796:36)
    at parseUrl (/Users/alex.mills/codes/magna/web/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)
    at toEndpointV1 (/Users/alex.mills/codes/magna/web/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:112:41)
    at customEndpointProvider (/Users/alex.mills/codes/magna/web/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65)


> nx run company:"graphql:generate-client"  [existing outputs match the cache, left as is]

[STARTED] Parse Configuration

```
