### ISSUE TITLE
@aws-sdk node client bump to the latest version(v3.679) got "TypeError: (0 , u.resolvedPath) is not a function" in @smithy/core

### ISSUE THREAD

**Issue by gzhao-atlas** [smithy-lang/smithy-typescript#1441]
We are trying to bump all the @aws-sdk node clients to the latest but got this error

```
TypeError: (0 , u.resolvedPath) is not a function
    at /var/task/lambda.js:1:128500
    at h.build (/var/task/lambda.js:1:128096)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
build js file reference here 

```
jmFJG:[function(e,t,r){var s=e("@parcel/transformer-js/src/esmodule-helpers.js");s.defineInteropFlag(r),s.export(r,"resolvedPath",()=>o.resolvedPath);var o=e("@smithy/core/protocols")},{"@smithy/core/protocols":"1X6cR","@parcel/transformer-js/src/esmodule-helpers.js":"kUWD7"}],
```
seems @smithy/core didn't export the function correctly? Anyone has ideas?

**Comment by dyarfaradj** [comment]
Same issue

**Comment by kuhe** [comment]
this issue is explained and fixed here https://github.com/smithy-lang/smithy-typescript/pull/1453

released in https://www.npmjs.com/package/@smithy/core/v/2.5.2
